name: .venv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - lightfm=1.16
  - numpy=1.20.3
  - pandas=1.5.3
  - scikit-surprise=1.1.3
  - ipykernel=6.29.5
  - matplotlib=3.7.1
  - scikit-learn=1.6.1
  - cornac=2.2.2
  - pytorch=1.12.1
  - seaborn=0.13.2
  
